name: remote ssh command
on:
  # Triggers the workflow on push or pull request events but only for the "devel" branch
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: "bash publicarAD.sh"
