name: remote ssh command
on:
  # Triggers the workflow on push or pull request events but only for the "devel" branch
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # Invocar Comando Servidor Remoto
      - name: Crear SSH key
        run: |
          install -m 600 -D /dev/null ~/SmartCode
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/SmartCode
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 140.84.178.147:22
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: "bash publicarAD.sh"
